### ISSUE TITLE
Not working in Glyphs2

### ISSUE THREAD

**Issue by ammazzarella** [mekkablue/ShowInterpolations#1]
When activating in G2, I get this error message:
glyphInterpolation: 'NSKVONotifying_GSGlyph' object has no attribute 'decomposedInterpolate_'

**Comment by mekkablue** [comment]
The incompatibility issue goes further than originally assumed:
A. The plugin seems to break the preview in G2.
B. The shortcut collides with the app default for a background command in G2.

**Comment by mekkablue** [comment]
Should be fixed by now.
