### ISSUE TITLE
Centering interpolations affects spacing of bottom preview bar

### ISSUE THREAD

**Issue by kontur** [mekkablue/ShowInterpolations#12]
When centering is turned on the sidebearings of the interpolated preview glyphs in a "show all" selection seem to get altered depending on what master is active. See below three screenshots

![light](http://johannesneumeier.com/tmp/b1.png)
![regular](http://johannesneumeier.com/tmp/b2.png)
![bold](http://johannesneumeier.com/tmp/b3_.png)

**Comment by mekkablue** [comment]
Sorry I never replied. The screenshots are not available anymore:

<img width="79" alt="screen shot 2018-02-23 at 18 04 52" src="https://user-images.githubusercontent.com/1103103/36606456-1010b842-18c4-11e8-8034-62269ddcb35e.png">

But do metrics matter in _Show All?_ You only see a single glyph.

**Comment by kontur** [comment]
Hey, sorry for late reply myself.

[Here a video showing the issue](https://drive.google.com/open?id=1ljSi9AZx_PP-Pw2saO1_Ika071uqyEUI).

It's not hugely problematic, but looks like buggy behaviour. It would be nice to not affect the bottom preview row at all - since in fact showing the interpolations does not affect them.
