### ISSUE TITLE
Interpolating anchor positions

### ISSUE THREAD

**Issue by kontur** [mekkablue/ShowInterpolations#13]
Have you considered also rendering anchors' interpolated positions? I occasionally find myself wanting to see that, but wonder if you'd feel this should be in the plugin?

**Comment by mekkablue** [comment]
Pffff. Anchors are not part of the exported outline. Anchor info goes into the feature code. _View > Show Compatibility_ connects anchors. Does this not suffice?

**Comment by kontur** [comment]
A use case for this is for example when I am viewing diacritics and wanting to visually check the anchor positions set in my masters follow a similar progression as the outlines themselves. I might try to hack this at a point, but opened the issue to get your view on it.

**Comment by mekkablue** [comment]
I added an undocumented option com.mekkablue.ShowInterpolation.anchors, set it to 1, and you will see the anchors.

`Glyphs.defaults["com.mekkablue.ShowInterpolation.anchors"] = 1`

**Comment by kontur** [comment]
Cool, thanks for this!

I was wondering how I could color the anchors in the interpolation instance to better see which anchor goes with which instance. For example to have the same hue, but different brightness. Do you know why the colors you now set are created as `NSColor` in the `colorForParameterValue` method actually are returned of type `NSCalibratedRGBColorSpace`? I tried to use [NScolor.blended()](https://developer.apple.com/documentation/appkit/nscolor/1524689-blended) to interpolate with white, for example, but got stuck with not actually having a NSColor object.

Another note, for me the anchors were showing by default, no setting required. Is this only set as 0 for new installs? But shouldn't the absence of the setting also evaluate as false?

**Comment by mekkablue** [comment]
> Another note, for me the anchors were showing by default, no setting required. Is this only set as 0 for new installs? But shouldn't the absence of the setting also evaluate as false?

That is the ‘GlyphsToolHand’ bug. I just posted about it in the Glyphs forum.
