### ISSUE TITLE
Allow displaying disabled instances?

### ISSUE THREAD

**Issue by madig** [mekkablue/ShowInterpolations#16]
I have a three master setup where I commonly adjust the extremes to more closely match the middle master. I made a fake middle instance that disables interpolation from the actual middle master to get something to compare against and set the `ShowInterpolations` parameter to both real and fake middle instances, but the plugin actively skips disabled instances. I have to keep the fake instance enabled and would need to toggle it off before export etc. Would it make sense to change this plugin to also look for disabled instances (maybe with a `ShowInterpolationEvenWhenDisabled` parameter) or is there a better way to do this?

**Comment by mekkablue** [comment]
I think I can add a hidden preference.

**Comment by mekkablue** [comment]
Update and run this in your Macro Window:

    Glyphs.defaults["com.mekkablue.ShowInterpolation.showDisabledInstances"]=True
