### ISSUE TITLE
Plugin broken in Glyphs 2.6.2?

### ISSUE THREAD

**Issue by madig** [mekkablue/ShowInterpolations#17]
Open a font, e.g. https://github.com/googlefonts/noto-source/blob/master/src/NotoSans-MM.glyphs or https://github.com/IBM/plex/blob/master/IBM-Plex-Sans-Variable/sources/IBMPlexSansVar-Roman.designspace.

Showing interpolations does nothing (or just shows one layer and nothing for the others) or with the latter file displays the following backtrace:

```
Traceback (most recent call last):
  File "plugin.py", line 148, in glyphInterpolation
    interpolatedLayer = interpolatedFont.glyphForName_(thisGlyph.name).layers[0]
AttributeError: 'NoneType' object has no attribute 'glyphForName_'

[... repeated multiple times ...]
```

**Comment by kontur** [comment]
Same result but different error for me in 2.6.2 — just updated GlyphsApp to 2.6.3 and the plugin works again.

**Comment by madig** [comment]
Do you mean the development version? @mekkablue will there be a hotfix release for 2.6.2? I prefer to stay on stable versions.
