### ISSUE TITLE
Center at user selected node?

### ISSUE THREAD

**Issue by impallari** [mekkablue/ShowInterpolations#18]
No longer available?

**Comment by alerque** [comment]
@impallari? *The* Pablo Impallari? HE LIVES!

**Comment by mekkablue** [comment]
Been a while. I vaguely remember it was not working well, so I disabled it, I think.

**Comment by kontur** [comment]
Been looking at this and trying to debug why the centering does not take any effect.

I replaced [this](https://github.com/mekkablue/ShowInterpolations/blob/01e53ed16b209e1b23724a3990e2a43359c73408/ShowInterpolation.glyphsReporter/Contents/Resources/plugin.py#L125) with:

```
print("before", interpolatedLayer.bounds.origin.x, interpolatedLayer.bounds.size.width)
interpolatedLayer.applyTransform([0.5, 0, 0, 0.5, 333, 0])
print("after", interpolatedLayer.bounds.origin.x, interpolatedLayer.bounds.size.width)
```

and get output that would indicate transforms are not applied at all, e.g.

> before 23.0 23.0
after 23.0 23.0
before 16.0 16.0
after 16.0 16.0
before 11.0 11.0
after 11.0 11.0

I'd expect the copied background layer to be shrunk by half, and offset 333 units to the right.

I'm also wondering if [painting to the layer](https://github.com/mekkablue/ShowInterpolations/blob/01e53ed16b209e1b23724a3990e2a43359c73408/ShowInterpolation.glyphsReporter/Contents/Resources/plugin.py#L129) with `interpolatedLayer.bezierPath.fill()` respects any transformations, or if it is just the python wrapper that does not get applied? 

E.g. the following will apply the transformation:
```
p = interpolatedLayer.completeBezierPath
p.applyTransform_([0.5, 0, 0, 0.5, 333, 0])
p.fill()
```

What's working and not working as intended here, maybe @schriftgestalt can say? Should I do the centering the `completeBezierPath` or is the API not doing what it should?

P.S.: The API says "The layer as an NSBezierPath object including paths from components. Useful for drawing glyphs in plug-ins." However, without [this bit](https://github.com/mekkablue/ShowInterpolations/blob/01e53ed16b209e1b23724a3990e2a43359c73408/ShowInterpolation.glyphsReporter/Contents/Resources/plugin.py#L156) components are not actually decomposed and do not get rendered at all in the background drawing.

**Comment by schriftgestalt** [comment]
I added the lines and get this:
```
before 358.0 0.0
after 512.0 0.0
```

What version of Glyphs do you have?

And you are linking to an older version of the code (the current version has different user default keys).

**Comment by kontur** [comment]
I just did this to confirm, on 3.1.2 (3149) and "Python version: 3.9.1 (Glyphs)":

Remove the plugin by removing the Reporter alias from the Plugins folder, and removing the ShowInterpolations folder from the Repositories folder.

Opened Glyphs, installed the "Show Styles" plugin via the plugin manager.

Closed Glyphs.

Edited the fresh copy of `/Users/johannes/Library/Application Support/Glyphs 3/Repositories/ShowInterpolations/ShowStyles.glyphsReporter/Contents/Resources/plugin.py` L. 143 as described above. 

Reopening Glyphs I am still getting the trace with before and after being the same.

**Comment by schriftgestalt** [comment]
I had tested it in 3.2 first and there it works. So it is fixed.

**Comment by kontur** [comment]
What are you saying? Do you mean that once 3.2 is released this will not be an issue any more, or that you cannot reproduce what I am reporting?

**Comment by schriftgestalt** [comment]
I mean I didn't see the problem at first because it works as expected in 3.2. I can reproduce it in 3.1.2.

**Comment by kontur** [comment]
Roger. Let' un-close this. This observation was just part of my trying to debug/fix, not sure if it is the root cause; and even if it boils down to just that, it should remain open until 3.2 is public, or a 3.1.x fixes it.
