### ISSUE TITLE
Missing context menu: Center interpolations

### ISSUE THREAD

**Issue by mirelabelova** [mekkablue/ShowInterpolations#19]
Center interpolations context menu is not showing by right-clicking in Glyphs 3.0.4
<img width="1130" alt="Screenshot 2021-12-02 at 12 20 34" src="https://user-images.githubusercontent.com/36231500/144403313-9f688701-1817-421f-962f-d09c637a0613.png">

**Comment by 75th** [comment]
I can further add to this that running the following script in the Macro panel doesn't change anything about the shown interpolations:

    Glyphs.clearLog();
    Glyphs.defaults["com.mekkablue.ShowStyles.centering"] = not Glyphs.defaults["com.mekkablue.ShowStyles.centering"]
    Glyphs.font.currentTab.forceRedraw()
    print(Glyphs.defaults["com.mekkablue.ShowStyles.centering"])

The last line shows the value toggling but that doesn't reflect in the rendering.

**Comment by mekkablue** [comment]
I think I took it out at one point because it would not work as expected.

**Comment by kontur** [comment]
Needed this but come to find these issues related to centering being open. Trying to fix it myself, I get this for whenever I open the right-click context menu with _this_ plugin:

```
GlyphsApp/GlyphsApp/plugins.py:93: UninitializedDeallocWarning: leaking an uninitialized object of type NSMenuItem
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1287, in addMenuItemsForEvent_toMenu_
  File "GlyphsApp/GlyphsApp/plugins.py", line 93, in setUpMenuHelper
ValueError: depythonifying 'SEL', got 'function'
```

What is more weird, I get this even if I uncomment near all of this plugins content (which otherwise takes effect). Is this some residue from the plugin rename or what is going on here?

**Comment by kontur** [comment]
Okay, no idea how _some_ plugins run the context menu code without error, and _some_ don't. I've made a fresh Reporter plugin copy from the SDK, the contextMenu works. I've added minimal code over to that new plugin like so:

```
# encoding: utf-8
from __future__ import division, print_function, unicode_literals


###########################################################################################################
#
#
#	Reporter Plugin
#
#	Read the docs:
#	https://github.com/schriftgestalt/GlyphsSDK/tree/master/Python%20Templates/Reporter
#
#
###########################################################################################################

import objc
from GlyphsApp import *
from GlyphsApp.plugins import *

class Test(ReporterPlugin):

	@objc.python_method
	def settings(self):
		self.menuName = Glyphs.localize({
			'en': 'Styles',
			'de': 'Stile',
			'es': 'estilos',
			'fr': 'styles',
			'pt': 'estilos',
			'zh': '💗插值',
		})
		
	@objc.python_method
	def conditionalContextMenus(self):
		print("HELLO CONTEXT MENU")
		# Add context menu item
		return [{
			'name': Glyphs.localize({
				'en': 'Do something else',
				'de': 'Tu etwas anderes',
				'fr': 'Faire aute chose',
				'es': 'Hacer algo más',
				'pt': 'Faça outra coisa',
				}), 
			'action': lambda x: print("HELLO")
			}]

	@objc.python_method
	def __file__(self):
		"""Please leave this method unchanged"""
		return __file__
```

And I get:
```
HELLO CONTEXT MENU
GlyphsApp/GlyphsApp/plugins.py:93: UninitializedDeallocWarning: leaking an uninitialized object of type NSMenuItem
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1287, in addMenuItemsForEvent_toMenu_
  File "GlyphsApp/GlyphsApp/plugins.py", line 93, in setUpMenuHelper
ValueError: depythonifying 'SEL', got 'function'
```

This is on 3.1.2 (3149).

cc @schriftgestalt

**Comment by schriftgestalt** [comment]
I fixed it. The methods that are used in callbacks shouldn’t be marked as `@objc.python_method`.

**Comment by schriftgestalt** [comment]
So `'action': lambda x: print("HELLO")` will not work. It has to be a method on an object inheriting from NSObject.

**Comment by kontur** [comment]
Cheers! I had the lambda in there just for testing, but alas I didn't spot the missing decorator either when comparing to other plugins. A more informative error would be great :)

**Comment by schriftgestalt** [comment]
That error is from pyobjc. And I think there was a change internal to pyobjc that it is now more strict.
