### ISSUE TITLE
Rounding to integers

### ISSUE THREAD

**Issue by Mark2Mark** [mekkablue/ShowInterpolations#4]
There seems to be a problem with the rounding of the interpolation-display. Best tested with rectangle shapes that align to another rectangles flank in all/both masters. See [Glyphs forum thread](https://forum.glyphsapp.com/t/tidy-up-path-on-export-custom-parameter/3724/11)

**Comment by mekkablue** [comment]
Can you (a) try if 2.0.3 fixes this (I use a different method for deriving the interpolations), and (b) if it doesn't, send me a glyph where this happens?

**Comment by Mark2Mark** [comment]
Thanks for checking. I made some samples with the file I think was affected. It seems to bee good now. I tried the /H, where the vertical stems are components and the horizontal bar (path rectangle) exactly ends on the outer side of these stems. It was giving these rounding issues back in the day, now they are perfectly aligned. Thank you!
