### ISSUE TITLE
3-Master Centering broken

### ISSUE THREAD

**Issue by chasnix** [mekkablue/ShowInterpolations#6]
The centering of interpolations is broken when there are three masters.

<img width="326" alt="screen shot 2016-08-25 at 2 30 05 pm" src="https://cloud.githubusercontent.com/assets/13006765/17986625/7a43865c-6ad0-11e6-91df-018781c2f559.png">

**Comment by mekkablue** [comment]
I gave this some more thought, and it should not center by default. Will add an option.

**Comment by impallari** [comment]
The thing is... each letter needs a different centering origin.

For example: 
/n or /b centered in the right contour of the first stem. 
/u  or /d centered in the left contour of the second stem, 
/o or /c centered in the bottom_center node (not the advance-width center). 
Letters for other script (deva, etc) also need different centers....

What about enabling the user to indicate the desired center?
If we can "tag" a node, or maybe adding a guideline having a custom name, or something else... I don't know...

**Comment by impallari** [comment]
Another thing... 
In multi-axis fonts, it will be nice to able to see interpolation per-axis.
For example, seeing weight interpolation only, or seeing width interpolations only.
Showing All the interpolations at the same time becomes a big mess and so it becomes useless.

**Comment by mekkablue** [comment]
The latest update includes a center option in the context menu.

@impallari You can already take care of selective display with the parameter or with activating/deactivating instances. I’ll think about the node-tagging.

**Comment by impallari** [comment]
Thanks Mekka!
Setting 40 instances On/Off manually is a PITA, so I just inaugurated my "Glyphs Macros" Repo and made a bunch of script to automate it
https://github.com/impallari/Impallari-Glyphs-Macros/tree/master/Instances/Show%20Hide

**Comment by chasnix** [comment]
Thanks, Rainer! You're superb!
