### ISSUE TITLE
Corner Serifs

### ISSUE THREAD

**Issue by weidemuller** [mekkablue/ShowInterpolations#7]
Hi,

I've trouble using the corner element in glyphs. Doesn't matter if I re-use one corner and turn around the position or make corners for top/bottom-right/left. Glyphs like "V" always cause bugs, corners on "p" or "q" are okay.
Can't really figure out the issue, hope you know whats wrong.

Thanks

![screen shot 2017-03-02 at 10 44 24](https://cloud.githubusercontent.com/assets/26138210/23504293/1231f658-ff3f-11e6-9826-37cd3cda122d.png)

**Comment by mekkablue** [comment]
Can you try version 2.0.3 of the plugin, I think I fixed it.
