### ISSUE TITLE
Really slow with last update

### ISSUE THREAD

**Issue by TypeNurse** [mekkablue/ShowInterpolations#8]
Latest update is really slow, and slows Glyphs (983) down as well. Tried several projects with various amount of masters and instances with same result.

**Comment by mekkablue** [comment]
The projects I tested seem fine. Can you send me a project that is noticeably slow? res at glyphsapp dot com, TIA.

**Comment by mekkablue** [comment]
OK, I think I found the point in the code that made it slow.
Try again with the version I just uploaded.

**Comment by TypeNurse** [comment]
Works great now. Thank you!
