### ISSUE TITLE
Interpolation are shaking

### ISSUE THREAD

**Issue by harbortype** [mekkablue/ShowInterpolations#9]
The interpolations shake when I click and drag anywhere on canvas. The same thing happens when I have Show Crosshair or Show Stem Thickness turned on.

Here is a short video: https://www.dropbox.com/s/f8eii0dchsy066c/Glyphs%20Show%20Interpolations.mov?dl=0

I’m on Glyphs 2.4.1 (983).

**Comment by kontur** [comment]
Not sure if this is the same, but for all it's worth I had a similar looking problem with shaking interpolations between uneven numbers. I'd nudge a master 1 unit more left or right and the shaking stops.

**Comment by mekkablue** [comment]
That is a rounding error when you have the centering option on. I do not know if I can do much about it.

EDIT: I could do floor division, which could stop the flickering, but then the result is not precise anymore. I recommend you simply turn of centering through the context menu.

**Comment by harbortype** [comment]
Ah, that’s ok. I’ll just disable centering then.

**Comment by kontur** [comment]
Found the centering helpful, so I tried to create a workaround to prevent this jitter. Please test the PR some more still, but for me this works by checking if the new interpolation should be moved at least 1 pixel, and if not, leaves the layer unmoved.

**Comment by harbortype** [comment]
Thank you, @kontur. It works for me.

**Comment by kontur** [comment]
After two days of using this fix just fine I found another glyph where the interpolations still wobble, despite the attempted fix it he PR. I will have a look at it if I get around to it, but thought I share the [test file](https://www.dropbox.com/s/c0aies7aufx95j4/wobble-comma.glyphs?dl=0) for testing, if anybody else wants to have  look.

**Comment by kontur** [comment]
Actually, those wobbles I now have are not the entire glyph jumping, but single nodes that have rounding problems in their interpolations. My above fix works for when the overall glyph widths result in rounding issues, but the internal per-glyph interpolations are unaffected - but can still cause problems. Presumably the same approach is viable.

**Comment by kontur** [comment]
(Disregard my previous deleted comments, somehow the repo HEAD was at the wrong commit -  my fix seems to work to prevent the jitter, as far as I can tell after two days usage.)
